//! Custom repro sequences: an escape hatch for callers who want to supply
//! their own ordered list of steps instead of (or as a starting point
//! derived from) the one this library auto-generates from a PDX.
//!
//! A custom sequence is plain JSON, authored by hand or generated by a
//! tool, and deliberately looks almost like [`crate::ReproSequence`]'s own
//! output — minus the fields that are only meaningful as *output*
//! (`index`, `step_count`), which are computed automatically. See
//! `docs/custom-sequence-guide.md` in the repository for the full guide
//! and `samples/custom-sequence.example.json` for a worked example.

use std::path::Path;

use serde::Deserialize;

use crate::error::{ReproError, Result};
use crate::sequence::{MessageSpec, ReproSequence, SequenceStep, StepCategory};

/// The JSON shape a user hand-writes (or a tool generates) to describe a
/// custom repro sequence.
#[derive(Debug, Deserialize)]
pub struct CustomSequenceInput {
    /// Optional; if omitted, the ECU variant name from the PDX passed
    /// alongside this file is used instead.
    #[serde(default)]
    pub ecu_variant: Option<String>,
    pub steps: Vec<CustomStepInput>,
}

/// One step in a hand-authored custom sequence. Every field except `name`
/// is optional so a minimal step is just `{"name": "...", "request": {...}}`.
#[derive(Debug, Deserialize)]
pub struct CustomStepInput {
    pub name: String,
    /// One of the `StepCategory` values (e.g. `"SESSION_CONTROL"`,
    /// `"TRANSFER_DATA"`); defaults to `"OTHER"`, which is the right
    /// choice for a step this library has no built-in meaning for (a
    /// vendor-specific routine, a deliberate delay, an extra check).
    #[serde(default)]
    pub category: StepCategory,
    #[serde(default)]
    pub semantic: Option<String>,
    #[serde(default)]
    pub request: Option<MessageSpec>,
    #[serde(default)]
    pub expected_positive_responses: Vec<MessageSpec>,
    #[serde(default)]
    pub expected_negative_responses: Vec<MessageSpec>,
    #[serde(default)]
    pub notes: Option<String>,
}

/// Load and validate a custom sequence file. `ecu_variant_fallback` is
/// used only when the file itself doesn't set `ecu_variant` (normally the
/// ECU variant name read from the PDX passed alongside this file).
pub fn load_custom_sequence_file(
    path: &Path,
    ecu_variant_fallback: Option<String>,
) -> Result<ReproSequence> {
    let raw = std::fs::read_to_string(path).map_err(|source| ReproError::ReadCustomSequence {
        path: path.to_path_buf(),
        source,
    })?;

    let input: CustomSequenceInput =
        serde_json::from_str(&raw).map_err(|source| ReproError::ParseCustomSequence {
            path: path.to_path_buf(),
            source,
        })?;

    if input.steps.is_empty() {
        return Err(ReproError::EmptyCustomSequence {
            path: path.to_path_buf(),
        });
    }

    let steps: Vec<SequenceStep> = input
        .steps
        .into_iter()
        .enumerate()
        .map(|(index, step)| SequenceStep {
            index,
            name: step.name,
            category: step.category,
            semantic: step.semantic,
            request: step.request,
            expected_positive_responses: step.expected_positive_responses,
            expected_negative_responses: step.expected_negative_responses,
            notes: step.notes,
        })
        .collect();

    Ok(ReproSequence {
        ecu_variant: input
            .ecu_variant
            .or(ecu_variant_fallback)
            .unwrap_or_else(|| "unknown".to_string()),
        step_count: steps.len(),
        steps,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sequence::FieldKind;

    fn write_temp_json(contents: &str) -> tempfile::NamedTempFile {
        use std::io::Write;
        let mut file = tempfile::NamedTempFile::new().unwrap();
        file.write_all(contents.as_bytes()).unwrap();
        file
    }

    #[test]
    fn loads_minimal_custom_sequence() {
        let file = write_temp_json(
            r#"{
                "steps": [
                    { "name": "CustomWait", "notes": "wait 500ms for ECU to settle" },
                    {
                        "name": "VendorRoutine",
                        "category": "OTHER",
                        "request": {
                            "name": "VendorRoutine_Req",
                            "fields": [
                                { "name": "SID", "kind": "fixed", "value_hex": "31" }
                            ]
                        }
                    }
                ]
            }"#,
        );

        let sequence =
            load_custom_sequence_file(file.path(), Some("Fallback_ECU".to_string())).unwrap();

        assert_eq!(sequence.ecu_variant, "Fallback_ECU");
        assert_eq!(sequence.step_count, 2);
        assert_eq!(sequence.steps[0].index, 0);
        assert_eq!(sequence.steps[0].category, StepCategory::Other);
        assert_eq!(sequence.steps[1].index, 1);

        let req = sequence.steps[1].request.as_ref().unwrap();
        match &req.fields[0].kind {
            FieldKind::Fixed { value_hex } => assert_eq!(value_hex, "31"),
            _ => panic!("expected fixed field"),
        }
    }

    #[test]
    fn ecu_variant_in_file_overrides_fallback() {
        let file = write_temp_json(
            r#"{
                "ecu_variant": "Explicit_ECU",
                "steps": [ { "name": "Step1" } ]
            }"#,
        );

        let sequence =
            load_custom_sequence_file(file.path(), Some("Fallback_ECU".to_string())).unwrap();
        assert_eq!(sequence.ecu_variant, "Explicit_ECU");
    }

    #[test]
    fn rejects_empty_steps() {
        let file = write_temp_json(r#"{ "steps": [] }"#);
        let err = load_custom_sequence_file(file.path(), None).unwrap_err();
        assert!(matches!(err, ReproError::EmptyCustomSequence { .. }));
    }

    #[test]
    fn parses_the_repository_sample_custom_sequence() {
        let sample_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../samples/custom-sequence.example.json");
        let sequence = load_custom_sequence_file(&sample_path, None)
            .expect("samples/custom-sequence.example.json must stay valid");
        assert_eq!(sequence.ecu_variant, "Sample_ECU");
        assert_eq!(sequence.step_count, 9);
        let vendor_step = sequence
            .steps
            .iter()
            .find(|s| s.name == "VendorPreFlashSelfTest")
            .expect("sample should contain the spliced-in vendor step");
        assert_eq!(vendor_step.category, StepCategory::Other);

        assert!(
            crate::validate_sequence(&sequence).is_empty(),
            "samples/custom-sequence.example.json should never trip the validator"
        );
    }

    #[test]
    fn rejects_invalid_category() {
        let file = write_temp_json(
            r#"{ "steps": [ { "name": "Bad", "category": "NOT_A_REAL_CATEGORY" } ] }"#,
        );
        let err = load_custom_sequence_file(file.path(), None).unwrap_err();
        assert!(matches!(err, ReproError::ParseCustomSequence { .. }));
    }
}
