<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>ReproToolkit.Example</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReproToolkit.Interop\ReproToolkit.Interop.csproj" />
  </ItemGroup>

</Project>
